# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5c754ffc5608ebc13531401486fa8b2c957350f43972acfbbde7209a868ff4648439c39fc6fa0e82f3bfb75b4035541e73f301674fdfe1cfb93e3272658f95b8

test:
  secret_key_base: e9b3a6695b3c9afc7f54bab8742222aec3eb32d505ba07eaa1d04249903e8a3adebc3a20bfd532fba8133991af361010fc0aa1efb3c978ac6b15e60d39e6b8a2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
